// tests/monthPageLayout.test.ts
var import_node_assert = require("node:assert");
var import_node_fs = require("node:fs");
var import_node_test = require("node:test");
(0, import_node_test.test)("keeps the vertical long-task timeline exclusive to long-task month mode", () => {
  const source = (0, import_node_fs.readFileSync)("src/ui/pages/MonthPage.ts", "utf8");
  import_node_assert.strict.match(source, /if \(viewMode === "long"\)[\s\S]*renderGroupedPool[\s\S]*renderLongVerticalTimeline/);
  import_node_assert.strict.match(source, /renderGroupedPool\(shell\.createDiv\(\{ cls: "cb-panel cb-task-pool" \}\), plugin, model, viewMode\);[\s\S]*renderPointMonthGrid/);
  import_node_assert.strict.match(source, /renderPointMonthGrid\(/);
  import_node_assert.strict.doesNotMatch(source, /function renderPointPool\(/);
  import_node_assert.strict.doesNotMatch(source, /buildPointTimelineRows/);
});
(0, import_node_test.test)("renders long-task month ranges as vertical timeline bars", () => {
  const source = (0, import_node_fs.readFileSync)("src/ui/pages/MonthPage.ts", "utf8");
  const longCard = source.slice(source.indexOf("function renderLongPoolTask"), source.indexOf("function renderTaskTitle"));
  const timeline = source.slice(source.indexOf("function renderLongVerticalTimeline"), source.indexOf("function setupTimelineDateTarget"));
  import_node_assert.strict.doesNotMatch(longCard, /unscheduledReason/);
  import_node_assert.strict.match(timeline, /cb-long-vertical-timeline/);
  import_node_assert.strict.match(timeline, /cb-long-vertical-track/);
  import_node_assert.strict.match(timeline, /for \(const row of rows\) renderLongVerticalTask\(track, plugin, row\)/);
  import_node_assert.strict.match(source, /function renderLongDatePicker/);
  import_node_assert.strict.doesNotMatch(timeline, /cb-timeline-row-track|cb-timeline-bar/);
});
(0, import_node_test.test)("renders month recurring task counts separately from concrete task counts", () => {
  const source = (0, import_node_fs.readFileSync)("src/ui/pages/MonthPage.ts", "utf8");
  const grid = source.slice(source.indexOf("function renderPointMonthGrid"), source.indexOf("function renderWeekdayHeader"));
  const css = (0, import_node_fs.readFileSync)("styles.css", "utf8");
  import_node_assert.strict.match(grid, /recurringTaskCount/);
  import_node_assert.strict.match(grid, /`\$\{load\.taskCount\}\/\$\{load\.recurringTaskCount\}`/);
  import_node_assert.strict.match(grid, /cb-day-load-breakdown/);
  import_node_assert.strict.match(grid, /cb-day-load-task/);
  import_node_assert.strict.match(grid, /cb-day-load-repeat/);
  import_node_assert.strict.match(grid, /renderDayLoadMetric/);
  import_node_assert.strict.match(grid, /cb-day-load-label/);
  import_node_assert.strict.match(grid, /cb-day-load-value/);
  import_node_assert.strict.match(grid, /cb-day-load-summary/);
  import_node_assert.strict.match(grid, /recurringTaskMinutes/);
  import_node_assert.strict.doesNotMatch(grid, /cb-recurring-task-count/);
  import_node_assert.strict.doesNotMatch(css, /cb-recurring-task-count/);
  import_node_assert.strict.match(css, /\.cb-day-load-breakdown/);
  import_node_assert.strict.match(css, /\.cb-day-load-repeat/);
  import_node_assert.strict.match(css, /\.cb-day-load-label/);
  import_node_assert.strict.match(css, /\.cb-day-load-value/);
});
(0, import_node_test.test)("maps month heat scores to continuous green orange red variables", () => {
  const source = (0, import_node_fs.readFileSync)("src/ui/pages/MonthPage.ts", "utf8");
  const css = (0, import_node_fs.readFileSync)("styles.css", "utf8");
  import_node_assert.strict.match(source, /const MONTH_HEAT_MAX_MINUTES = 14 \* 60/);
  import_node_assert.strict.match(source, /const MONTH_HEAT_MID_MINUTES = MONTH_HEAT_MAX_MINUTES \/ 2/);
  import_node_assert.strict.match(source, /const MONTH_HEAT_GREEN = \{ r: 54, g: 147, b: 95 \}/);
  import_node_assert.strict.match(source, /const MONTH_HEAT_ORANGE = \{ r: 208, g: 129, b: 36 \}/);
  import_node_assert.strict.match(source, /const MONTH_HEAT_RED = \{ r: 191, g: 75, b: 69 \}/);
  import_node_assert.strict.match(source, /applyMonthHeatStyle\(cell, load\.heatScore\)/);
  import_node_assert.strict.match(source, /function monthHeatStyle/);
  import_node_assert.strict.match(source, /interpolateHeatColor\(MONTH_HEAT_GREEN, MONTH_HEAT_ORANGE/);
  import_node_assert.strict.match(source, /interpolateHeatColor\(MONTH_HEAT_ORANGE, MONTH_HEAT_RED/);
  import_node_assert.strict.match(source, /Math\.min\(minutes, MONTH_HEAT_MAX_MINUTES\)/);
  import_node_assert.strict.match(source, /--cb-heat-r/);
  import_node_assert.strict.match(source, /--cb-heat-alpha/);
  import_node_assert.strict.doesNotMatch(source, /monthHeatLevel/);
  import_node_assert.strict.doesNotMatch(source, /is-heat-\$\{/);
  import_node_assert.strict.doesNotMatch(source, /minutes <= 120/);
  import_node_assert.strict.doesNotMatch(source, /minutes <= 240/);
  import_node_assert.strict.match(css, /--cb-heat-r:\s*0/);
  import_node_assert.strict.match(css, /--cb-heat-g:\s*0/);
  import_node_assert.strict.match(css, /--cb-heat-b:\s*0/);
  import_node_assert.strict.match(css, /--cb-heat-alpha:\s*0/);
  import_node_assert.strict.match(css, /rgba\(var\(--cb-heat-r\), var\(--cb-heat-g\), var\(--cb-heat-b\), var\(--cb-heat-alpha\)\)/);
  import_node_assert.strict.doesNotMatch(css, /\.cb-day-cell\.is-heat-low/);
  import_node_assert.strict.doesNotMatch(css, /\.cb-day-cell\.is-heat-medium/);
  import_node_assert.strict.doesNotMatch(css, /\.cb-day-cell\.is-heat-high/);
});
(0, import_node_test.test)("renders long-task planned and child-entry controls only in the task menu", () => {
  const source = (0, import_node_fs.readFileSync)("src/ui/pages/MonthPage.ts", "utf8");
  const menu = source.slice(source.indexOf("function openTaskMenu"), source.indexOf("async function applyTaskMenu"));
  import_node_assert.strict.match(menu, /if \(task\.taskKind === "long"\)/);
  import_node_assert.strict.match(menu, /task\.plannedDate === todayString\(\)/);
  import_node_assert.strict.match(menu, /Planned today/);
  import_node_assert.strict.match(menu, /Child task/);
  import_node_assert.strict.match(menu, /Add child/);
  import_node_assert.strict.match(source, /function addChildTaskFromMenu/);
  import_node_assert.strict.match(source, /plugin\.addLongTaskChild/);
});
(0, import_node_test.test)("keeps long-task context menu controls wide and single-line", () => {
  const css = (0, import_node_fs.readFileSync)("styles.css", "utf8");
  const menu = css.slice(css.indexOf(".cb-task-context-menu"), css.indexOf(".modal:has(.cb-archive-modal)"));
  import_node_assert.strict.match(menu, /width:\s*min\(480px,\s*calc\(100vw - 24px\)\)/);
  import_node_assert.strict.match(menu, /grid-template-columns:\s*112px minmax\(0,\s*1fr\)/);
  import_node_assert.strict.match(menu, /input\[type="checkbox"\][\s\S]*width:\s*18px/);
  import_node_assert.strict.match(menu, /input\[type="checkbox"\][\s\S]*height:\s*18px/);
  import_node_assert.strict.match(menu, /\.cb-menu-actions\s*\{[\s\S]*display:\s*grid/);
  import_node_assert.strict.match(menu, /grid-template-columns:\s*auto auto minmax\(max-content,\s*1fr\) auto/);
  import_node_assert.strict.match(menu, /white-space:\s*nowrap/);
});
(0, import_node_test.test)("filters scheduled daily files only for month long-task mode", () => {
  const source = (0, import_node_fs.readFileSync)("src/ui/pages/MonthPage.ts", "utf8");
  const render = source.slice(source.indexOf("export function renderMonthPage"), source.indexOf("function renderGroupedPool"));
  import_node_assert.strict.match(render, /const viewMode: MonthTaskViewMode = plugin\.data\.ui\.monthTaskViewMode \?\? "point"/);
  import_node_assert.strict.match(render, /viewMode === "long"[\s\S]*isScheduledDayFilePath\(task\.filePath, plugin\.data\.settings\.scheduledDayFolder\)/);
  import_node_assert.strict.match(render, /: plugin\.calendarTasks/);
  import_node_assert.strict.match(source, /export function isScheduledDayFilePath/);
  import_node_assert.strict.match(source, /\^\\d\{8\}\\\.md\$/);
});
(0, import_node_test.test)("renders vertical long-task timeline with non-overlapping lanes", () => {
  const source = (0, import_node_fs.readFileSync)("src/ui/pages/MonthPage.ts", "utf8");
  const timeline = source.slice(source.indexOf("function renderLongVerticalTimeline"), source.indexOf("function setupTimelineDateTarget"));
  import_node_assert.strict.match(source, /function assignVerticalTimelineLanes/);
  import_node_assert.strict.match(timeline, /cb-long-vertical-date-axis/);
  import_node_assert.strict.match(timeline, /cb-long-vertical-track/);
  import_node_assert.strict.match(timeline, /--cb-long-days/);
  import_node_assert.strict.match(timeline, /--cb-long-lanes/);
  import_node_assert.strict.match(source, /gridRow = `\$\{row\.startDay\} \/ \$\{row\.endDay \+ 1\}`/);
  import_node_assert.strict.match(source, /gridColumn = String\(row\.lane\)/);
});
(0, import_node_test.test)("uses the long-task red frame for behind pace status", () => {
  const source = (0, import_node_fs.readFileSync)("src/ui/pages/MonthPage.ts", "utf8");
  const css = (0, import_node_fs.readFileSync)("styles.css", "utf8");
  const task = source.slice(source.indexOf("function renderLongVerticalTask"), source.indexOf("function renderLongTaskChildren"));
  import_node_assert.strict.match(task, /toggleClass\("is-behind", row\.status === "behind"\)/);
  import_node_assert.strict.doesNotMatch(task, /toggleClass\("is-overdue"/);
  import_node_assert.strict.match(css, /\.cb-long-vertical-bar\.is-behind\s*\{/);
  import_node_assert.strict.match(css, /\.cb-long-vertical-bar\.is-behind\s*\{[^}]*var\(--text-error\)/s);
  import_node_assert.strict.doesNotMatch(css, /\.cb-long-vertical-bar\.is-overdue\s*\{/);
});
(0, import_node_test.test)("uses a green frame only on planned long-task timeline bars", () => {
  const source = (0, import_node_fs.readFileSync)("src/ui/pages/MonthPage.ts", "utf8");
  const css = (0, import_node_fs.readFileSync)("styles.css", "utf8");
  const poolTask = source.slice(source.indexOf("function renderLongPoolTask"), source.indexOf("function renderTaskTitle"));
  const timelineTask = source.slice(source.indexOf("function renderLongVerticalTask"), source.indexOf("function renderLongTaskChildren"));
  import_node_assert.strict.doesNotMatch(poolTask, /is-planned-today/);
  import_node_assert.strict.match(timelineTask, /toggleClass\("is-planned-today", isPlannedToday\(row\.task\)\)/);
  import_node_assert.strict.match(css, /\.cb-long-vertical-bar\.is-planned-today\s*\{/);
  import_node_assert.strict.match(css, /\.cb-long-vertical-bar\.is-planned-today\s*\{[^}]*var\(--text-success\)/s);
  import_node_assert.strict.doesNotMatch(css, /\.cb-long-task-card\.is-planned-today/);
});
(0, import_node_test.test)("lets long-task month timelines collapse and expand past days", () => {
  const source = (0, import_node_fs.readFileSync)("src/ui/pages/MonthPage.ts", "utf8");
  const timeline = source.slice(source.indexOf("function renderLongVerticalTimeline"), source.indexOf("function setupTimelineDateTarget"));
  import_node_assert.strict.match(source, /buildLongTimelineDisplay/);
  import_node_assert.strict.match(source, /longTaskPastDaysExpanded === true/);
  import_node_assert.strict.match(timeline, /renderLongPastDaysToggle/);
  import_node_assert.strict.match(source, /function toggleLongTaskPastDays/);
  import_node_assert.strict.match(source, /cb-long-past-toggle/);
  import_node_assert.strict.match(source, /day\.isFoldedPast/);
});
(0, import_node_test.test)("lets long-task month pool include every unscheduled candidate", () => {
  const source = (0, import_node_fs.readFileSync)("src/ui/pages/MonthPage.ts", "utf8");
  import_node_assert.strict.match(source, /function isTaskVisibleInPool/);
  import_node_assert.strict.match(source, /text: "Unscheduled tasks"/);
  import_node_assert.strict.doesNotMatch(source, /Unscheduled long tasks/);
  import_node_assert.strict.doesNotMatch(source, /Unscheduled point tasks/);
  import_node_assert.strict.match(source, /return true/);
  import_node_assert.strict.doesNotMatch(source, /triggerType !== "phase-note"/);
});
(0, import_node_test.test)("renders parent long-task labels in point pools and child tasks inside long-task bars", () => {
  const source = (0, import_node_fs.readFileSync)("src/ui/pages/MonthPage.ts", "utf8");
  import_node_assert.strict.match(source, /function renderParentLongTaskChip/);
  import_node_assert.strict.match(source, /renderParentLongTaskChip\(meta, task\)/);
  import_node_assert.strict.match(source, /function renderLongTaskChildren/);
  import_node_assert.strict.match(source, /renderLongTaskChildren\(bar, plugin, row\.childTasks\)/);
  import_node_assert.strict.match(source, /function childTaskScheduleLabel/);
});
(0, import_node_test.test)("renders recurring long-task children as compact child rows", () => {
  const source = (0, import_node_fs.readFileSync)("src/ui/pages/MonthPage.ts", "utf8");
  const css = (0, import_node_fs.readFileSync)("styles.css", "utf8");
  const children = source.slice(source.indexOf("function renderLongTaskChildren"), source.indexOf("function renderChildLongTaskCard"));
  import_node_assert.strict.match(children, /isRecurringTask\(child\)/);
  import_node_assert.strict.match(children, /renderRecurringChildTask\(list, child\)/);
  import_node_assert.strict.match(source, /function recurringCycleLabel/);
  import_node_assert.strict.match(source, /function recurringRefreshLabel/);
  import_node_assert.strict.match(source, /function weekdayLabel/);
  import_node_assert.strict.match(source, /cb-long-child-cycle/);
  import_node_assert.strict.match(source, /cb-long-child-refresh/);
  import_node_assert.strict.match(source, /刷新：/);
  import_node_assert.strict.match(css, /\.cb-long-child-recurring/);
  import_node_assert.strict.match(css, /\.cb-long-child-cycle/);
  import_node_assert.strict.match(css, /\.cb-long-child-refresh/);
});
(0, import_node_test.test)("renders scheduled child long tasks as draggable cards inside parent bars", () => {
  const source = (0, import_node_fs.readFileSync)("src/ui/pages/MonthPage.ts", "utf8");
  const css = (0, import_node_fs.readFileSync)("styles.css", "utf8");
  import_node_assert.strict.match(source, /function renderChildLongTaskCard/);
  import_node_assert.strict.match(source, /renderChildLongTaskCard\(list, plugin, child, schedule\)/);
  import_node_assert.strict.match(source, /item\.draggable = true/);
  import_node_assert.strict.match(source, /setDragTask\(event, task\.id\)/);
  import_node_assert.strict.match(css, /\.cb-long-child-card/);
  import_node_assert.strict.match(css, /\.cb-long-child-card-header/);
  import_node_assert.strict.match(css, /\.cb-long-child-card-range/);
});
(0, import_node_test.test)("keeps child long task drag ids from bubbling into the parent bar", () => {
  const source = (0, import_node_fs.readFileSync)("src/ui/pages/MonthPage.ts", "utf8");
  const childCard = source.slice(source.indexOf("function renderChildLongTaskCard"), source.indexOf("function renderParentLongTaskChip"));
  import_node_assert.strict.match(childCard, /event\.stopPropagation\(\)/);
  import_node_assert.strict.match(childCard, /setDragTask\(event, task\.id\)/);
});
(0, import_node_test.test)("keeps child long task titles readable beside range labels", () => {
  const css = (0, import_node_fs.readFileSync)("styles.css", "utf8");
  import_node_assert.strict.match(css, /\.cb-long-child-card-header\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)/s);
  import_node_assert.strict.match(css, /\.cb-long-child-card-title\s*\{[^}]*white-space:\s*normal/s);
  import_node_assert.strict.match(css, /\.cb-long-child-card-title\s*\{[^}]*overflow-wrap:\s*anywhere/s);
  import_node_assert.strict.match(css, /\.cb-long-child-card-range\s*\{[^}]*justify-self:\s*start/s);
});
(0, import_node_test.test)("lets compressed long-task bars scroll vertically", () => {
  const css = (0, import_node_fs.readFileSync)("styles.css", "utf8");
  const bar = css.slice(css.indexOf(".cb-long-vertical-bar {"), css.indexOf(".cb-long-vertical-bar.is-behind {"));
  import_node_assert.strict.match(bar, /overflow-y:\s*auto/);
});
(0, import_node_test.test)("opens the source note when month task titles are clicked", () => {
  const source = (0, import_node_fs.readFileSync)("src/ui/pages/MonthPage.ts", "utf8");
  const title = source.slice(source.indexOf("function renderTaskTitle"), source.indexOf("function renderLongVerticalTimeline"));
  const pointPool = source.slice(source.indexOf("function renderPointPoolTask"), source.indexOf("function renderLongPoolTask"));
  const longPool = source.slice(source.indexOf("function renderLongPoolTask"), source.indexOf("function renderTaskTitle"));
  const longBar = source.slice(source.indexOf("function renderLongVerticalTask"), source.indexOf("function renderLongTaskChildren"));
  const childCard = source.slice(source.indexOf("function renderChildLongTaskCard"), source.indexOf("function renderParentLongTaskChip"));
  import_node_assert.strict.match(title, /plugin: PersonalSchedulerPlugin/);
  import_node_assert.strict.match(title, /addEventListener\("click", \(\) => void plugin\.openTaskSourceNote\(task\.id\)\)/);
  import_node_assert.strict.match(pointPool, /renderTaskTitle\(card, plugin, task\)/);
  import_node_assert.strict.match(longPool, /renderTaskTitle\(card, plugin, task\)/);
  import_node_assert.strict.match(longBar, /renderTaskTitle\(bar, plugin, row\.task\)/);
  import_node_assert.strict.match(childCard, /openTaskSourceNote\(task\.id\)/);
});
