// tests/weekPageLayout.test.ts
var import_node_assert = require("node:assert");
var import_node_fs = require("node:fs");
var import_node_test = require("node:test");
(0, import_node_test.test)("renders week unscheduled pool with source grouping, sorting, and priority display", () => {
  const source = (0, import_node_fs.readFileSync)("src/ui/pages/WeekPage.ts", "utf8");
  import_node_assert.strict.match(source, /buildSourceTaskGroups/);
  import_node_assert.strict.match(source, /renderPool\(pool, plugin, model\.unifiedUnscheduledTasks\)/);
  import_node_assert.strict.doesNotMatch(source, /unifiedUnscheduledTasks\.filter\(\(task\) => task\.taskKind !== "long"\)/);
  import_node_assert.strict.match(source, /text: "Unscheduled tasks"/);
  import_node_assert.strict.match(source, /text: "No unscheduled tasks\."/);
  import_node_assert.strict.match(source, /function renderSourceGroup/);
  import_node_assert.strict.match(source, /function renderSortToggle/);
  import_node_assert.strict.match(source, /cb-priority-chip/);
  import_node_assert.strict.match(source, /cb-priority-marker/);
  import_node_assert.strict.match(source, /cb-week-task-list/);
  import_node_assert.strict.match(source, /cb-week-priority cb-priority-marker/);
  import_node_assert.strict.match(source, /cb-week-task-content/);
  import_node_assert.strict.match(source, /function shortPriorityLabel/);
  import_node_assert.strict.match(source, /priority === "medium"\) return "med"/);
  import_node_assert.strict.match(source, /shortPriorityLabel\(task\)/);
  import_node_assert.strict.match(source, /taskContentLabel\(task\)/);
  import_node_assert.strict.match(source, /cleanTaskContentText\(task\.rawLine\)/);
  import_node_assert.strict.doesNotMatch(source, /Before anchor/);
});
(0, import_node_test.test)("renders parent long-task labels on week unscheduled child tasks", () => {
  const source = (0, import_node_fs.readFileSync)("src/ui/pages/WeekPage.ts", "utf8");
  import_node_assert.strict.match(source, /function renderParentLongTaskChip/);
  import_node_assert.strict.match(source, /renderParentLongTaskChip\(meta, task\)/);
  import_node_assert.strict.match(source, /parentLongTaskText/);
});
(0, import_node_test.test)("renders week recurring task counts without scheduled recurring task names", () => {
  const source = (0, import_node_fs.readFileSync)("src/ui/pages/WeekPage.ts", "utf8");
  const css = (0, import_node_fs.readFileSync)("styles.css", "utf8");
  const dayRow = source.slice(source.indexOf("function renderDayRow"), source.indexOf("function renderPoolTask"));
  import_node_assert.strict.match(dayRow, /recurringTaskCount/);
  import_node_assert.strict.match(dayRow, /recurringTaskMinutes/);
  import_node_assert.strict.match(dayRow, /cb-week-day-summary/);
  import_node_assert.strict.match(dayRow, /renderWeekSummaryMetric/);
  import_node_assert.strict.match(dayRow, /cb-week-day-metric-label/);
  import_node_assert.strict.match(dayRow, /cb-week-day-metric-value/);
  import_node_assert.strict.match(dayRow, /cb-week-day-total/);
  import_node_assert.strict.match(dayRow, /cb-recurring-compact-summary/);
  import_node_assert.strict.match(dayRow, /repeat/);
  import_node_assert.strict.doesNotMatch(dayRow, /tasks\$\{recurringSummary\} \|/);
  import_node_assert.strict.doesNotMatch(dayRow, /renderScheduledTaskName\([^)]*recurring/i);
  import_node_assert.strict.match(css, /\.cb-week-day-summary/);
  import_node_assert.strict.match(css, /\.cb-week-day-metric/);
  import_node_assert.strict.match(css, /\.cb-recurring-compact-summary/);
  import_node_assert.strict.doesNotMatch(dayRow, /cb-recurring-summary/);
});
(0, import_node_test.test)("opens the source note when week task titles are clicked", () => {
  const source = (0, import_node_fs.readFileSync)("src/ui/pages/WeekPage.ts", "utf8");
  const title = source.slice(source.indexOf("function renderTaskTitle"), source.indexOf("function renderEstimateControl"));
  const scheduled = source.slice(source.indexOf("function renderScheduledTaskName"), source.indexOf("function renderTaskTitle"));
  import_node_assert.strict.match(title, /plugin: PersonalSchedulerPlugin/);
  import_node_assert.strict.match(title, /addEventListener\("click", \(\) => void plugin\.openTaskSourceNote\(task\.id\)\)/);
  import_node_assert.strict.match(source, /renderTaskTitle\(card, plugin, task\)/);
  import_node_assert.strict.match(scheduled, /openTaskSourceNote\(task\.id\)/);
});
